Add GLSP diagram editor extension
eclipse-theia/generator-theia-extension pull request #153
Opened 2022-08-09 07:57 UTC by planger

This extension can generate diagram editors based on the [GLSP examples](https://github.com/eclipse-glsp/glsp-examples) with Java or nodejs backend and package it as Theia extension or VS Code extension.

Co-authored-by: Max Elia <max_elia@hotmail.de>
Co-authored-by: Florian Gareis <dev@zoker.me>

Closes https://github.com/eclipse-theia/generator-theia-extension/issues/110

2022-08-09 08:53 UTC, JonasHelming requested changes
I was unable to generate the GLSP template with Node 12. We should probably introduce a dependecy on >= Node 14

2022-08-09 08:53 UTC, JonasHelming commented on src/app/index.ts
> +                    message: 'Which backend do you want?',
```suggestion
                    message: 'Which GLSP backend do you want to use, i.e. in which language do you prefer to develop your GLSP server?',
```

2022-08-09 08:53 UTC, JonasHelming commented on src/app/index.ts
> +                        message: 'Which editor do you want?',
```suggestion
                        message: 'Which extension mechanism do you want to use?',
```

2022-08-09 08:53 UTC, JonasHelming commented on src/app/index.ts
> +                            { value: TemplateType.NodeTheia, name: 'Theia' },
```suggestion
                            { value: TemplateType.NodeTheia, name: 'Theia extension (more features)' },
```

2022-08-09 08:53 UTC, JonasHelming commented on src/app/index.ts
> +                            { value: TemplateType.NodeVSCode, name: 'VSCode' },
```suggestion
                            { value: TemplateType.NodeVSCode, name: 'VSCode extension (compatible with VS Code)' },
```

2022-08-09 08:53 UTC, JonasHelming commented on src/app/index.ts
> +                    this.log('\x1b[32m%s\x1b[0m', 'The template will use an EMF source model and can be used for theia ✓')
```suggestion
                    this.log('\x1b[32m%s\x1b[0m', 'The template will use an EMF source model on the server and generate a Theia extension ✓')
```

2022-08-09 08:53 UTC, JonasHelming commented on src/app/index.ts
> +                    this.log('\x1b[32m%s\x1b[0m', 'The template will use a JSON based source model, node as a server and can be used for Theia ✓')
```suggestion
                    this.log('\x1b[32m%s\x1b[0m', 'The template will use a JSON based source model, node as a server and generate a Theia extension ✓')
```

2022-08-09 08:53 UTC, JonasHelming commented on src/app/index.ts
> +                    this.log('\x1b[32m%s\x1b[0m', 'The template will use a JSON based source model, node as a server and can be used for VSCode ✓')
```suggestion
                    this.log('\x1b[32m%s\x1b[0m', 'The template will use a JSON based source model, node as a server and generate a VSCode extension ✓')
```

2022-08-09 08:53 UTC, JonasHelming commented on src/app/index.ts
> +                        { value: 'node', name: 'Node' },
```suggestion
                        { value: 'node', name: 'Node (TypeScript)' },
```

2022-08-09 09:38 UTC, planger commented
> I was unable to generate the GLSP template with Node 12. We should probably introduce a dependecy on >= Node 14

Right, I guess that's also true for all other templates as Theia itself requires Node >= 14.

Anyway, we'll add an `engines` entry to the `package.json` of the GLSP project example and move the tag. I'll track that in https://github.com/eclipse-glsp/glsp/issues/676. Thus, this PR doesn't need to be changed in this regard.

2022-08-09 09:40 UTC, JonasHelming commented
> > I was unable to generate the GLSP template with Node 12. We should probably introduce a dependecy on >= Node 14
> 
> Right, I guess that's also true for all other templates as Theia itself requires Node >= 14.
> 
> Anyway, we'll add an `engines` entry to the `package.json` of the GLSP project example and move the tag. I'll track that in [eclipse-glsp/glsp#676](https://github.com/eclipse-glsp/glsp/issues/676). Thus, this PR doesn't need to be changed in this regard.

Yes and also: https://github.com/eclipse-theia/generator-theia-extension/issues/154

2022-08-09 09:41 UTC, JonasHelming approved these changes

2022-08-09 11:53 UTC, vince-fugnitto reviewed
The following comment brings up similar concerns I had with the previous pull-request (https://github.com/eclipse-theia/generator-theia-extension/pull/111#pullrequestreview-677657569):

> This extension can generate diagram editors based on the [GLSP examples](https://github.com/eclipse-glsp/glsp-examples) with Java or nodejs backend and package it as Theia extension or VS Code extension.

Do we really want to include a generator that is so specific, and which can also provide a vscode extension? The repository is meant to easily get started and create your own Theia extension but now we are starting to mix concepts. For something as specific as `glsp` is it not better in it's own repository? Is there a need to have it in the upstream generator?

2022-08-10 11:32 UTC, JonasHelming commented
> The following comment brings up similar concerns I had with the previous pull-request ([#111 (review)](https://github.com/eclipse-theia/generator-theia-extension/pull/111#pullrequestreview-677657569)):
> 
> > This extension can generate diagram editors based on the [GLSP examples](https://github.com/eclipse-glsp/glsp-examples) with Java or nodejs backend and package it as Theia extension or VS Code extension.
> 
> Do we really want to include a generator that is so specific, and which can also provide a vscode extension? The repository is meant to easily get started and create your own Theia extension but now we are starting to mix concepts. For something as specific as `glsp` is it not better in it's own repository? Is there a need to have it in the upstream generator?

For the VS Code extension path, I agree, I would simply remove it. For the Theia extension path, I would very much prefer to have it here. From the view point of a Theia user, it is an interesting capability to explore. Even if the diagram editor is provided by GLSP, it shows a strength of Theia. The generated template is a Theia extension + a Theia example application.
This question we already discussed here: https://github.com/eclipse-theia/generator-theia-extension/pull/111#issuecomment-856635841

So my proposal is to remove the VS Code path and keep the rest as is, are you fine with this? @vince-fugnitto

2022-08-10 11:49 UTC, vince-fugnitto commented
@JonasHelming I won't block the pull-request but I'm not entirely confident in the way we consume the `glsp-example` (it would likely be better suited as an example repository) and the fact we need to fetch the `tar.gz` and that it does not include any `template` file in this repository. I'm worried others may do the same and make the repository unmanageable (I already for instance cannot fix bugs in glsp).

If the way forward is to remove the vscode path then let's do that.

2022-08-10 12:15 UTC, JonasHelming commented
VS Code template has been removed

2022-08-11 07:36 UTC, merged

2022-08-11 07:36 UTC, JonasHelming commented
@vince-fugnitto Would it be possible to do a release of the generator?